### ISSUE TITLE
Support for Minus key seemingly not working

### ISSUE THREAD

**Issue by Raytwo** [blu-dev/ninput#1]
Heyo,

Seems like when you press Minus it no work, care to fix it OwO????

Here is code snippet so you can reproduce UwU
```rust
ninput::init();

if ninput::any::is_down(ninput::Buttons::MINUS) {
        println!("input");
    }```

**Comment by blu-dev** [comment]
![image](https://user-images.githubusercontent.com/42755519/161154620-6ad04025-b66f-4478-a0d8-a788b94740d4.png)

**Comment by Raytwo** [comment]
PRs not needed, everything works fine, thanks a lot for your assistance kind sir.
